name: cleanup

on:
  pull_request:
    types: [closed]

jobs:
  delete-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario: ['success', 'failure']
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: |
          pnpm run build
          pnpm run package

      - name: extract branch name
        id: get_branch
        run: |
          echo "branch=$(${PR_HEAD#refs/heads/} | tr / -)" >>"$GITHUB_OUTPUT"
        env:
          PR_HEAD: ${{ github.head_ref }}

      - name: delete environment
        uses: ./
        with:
          env: integration-test-${{ steps.get_branch.outputs.branch }}-${{ matrix.scenario }}
          step: delete-env
          debug: true
