name: Reviewdog

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  misspell:
    if: ${{ github.event.action != 'closed' }}
    name: Misspell
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-misspell@v1
        with:
          path: |
            src
            package.json
            *.md
            action.yml
            LICENSE
          exclude: |
            integration/tapview

  actionlint:
    if: ${{ github.event.action != 'closed' }}
    name: Actionlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1

  biome:
    if: ${{ github.event.action != 'closed' }}
    name: 'Typescript: Biome'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile

      - uses: mongolyy/reviewdog-action-biome@v1
